apiVersion: v1
kind: Pod
metadata:
  name: server-mesher
  annotations:
    sidecar.mesher.io/inject: "yes"
    sidecar.mesher.io/discoveryType: "pilot"
  labels:
    app: server-mesher
spec:
  containers:
    - name: server
      image: savita3020/server-io-go
      imagePullPolicy: Always
      ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: server-mesher
spec:
  selector:
    app: server-mesher
  ports:
  - protocol: TCP
    name: http
    port: 9999
