apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: default
  name: server-mesher
spec:
  selector:
    matchLabels:
      app: default
  template:
    metadata:
      annotations:
        sidecar.mesher.io/inject: "yes"
        sidecar.mesher.io/discoveryType: "pilot"
      labels:
        app: default
    spec:
      containers:
        - name: server
          image: savita3020/server-io-go
          imagePullPolicy: Always
          ports:
            - containerPort: 9999
---
apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: server-mesher
spec:
  selector:
    app: default
  ports:
  - protocol: TCP
    name: http
    port: 9999

