apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mesher-sidecar-injector-mesher-system
  labels:
    app: mesher-sidecar-injector
    chart: sidecarInjectorWebhook
rules:
- apiGroups: ["*"]
  resources: ["namespaces"]
  verbs: ["update", "create", "get", "list", "watch"]
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["update", "create", "get", "list", "watch"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "list", "watch", "patch"]