apiVersion: v1
kind: ConfigMap
metadata:
  name: sidecar-injector-webhook-mesher-configmap
data:
  sidecar_k8s_spec.yaml: |
    containers:
      - name: sidecar-mesher
        image: gomesh/mesher:latest
        imagePullPolicy: Always
        env:
          - name: SERVICE_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
          - containerPort: 30101
        volumeMounts:
          - name: mesher-conf
            mountPath: /tmp
    volumes:
      - name: mesher-conf
        configMap:
          name: mesher-configmap