apiVersion: v1
kind: ConfigMap
metadata:
  name: mesher-configmap
data:
  chassis.yaml: |
    ---
    cse:
      protocols:
        http:
          listenAddress: 127.0.0.1:30101
      service:
        registry:
          refreshInterval: 10s
          registrator:
            disabled: true
          serviceDiscovery:
            type: servicecenter
            address: http://service-center.servicecomb:30100
      config:
        client:
          type: config_center			# config_center/apollo
          #serverUri: http://127.0.0.1:30103
          refreshMode: 1
          refreshInterval: 30
          tenantName:  default
          autodiscovery: false
