apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: sidecar-injector-webhook-mesher-cfg
  labels:
    app: sidecar-injector
webhooks:
  - name: sidecar-injector.mesher.io
    clientConfig:
      service:
        name: sidecar-injector-webhook-mesher-svc
        namespace: servicecomb
        path: "/webhookmutation"
      caBundle: ""
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
